# Action名称
name: Publish NuGet Package 
# 设置触发器
on:
  # main分支无法push 所以直接使用push来作为接受pull request的触发条件即可
  push:
    branches:
      - main
  # 手动触发
  workflow_dispatch:
# 执行步骤
jobs:
  # 用Windows构建
  build-and-publish:
    runs-on: windows-latest
    steps:
      # 迁出
      - name: Checkout code
        uses: actions/checkout@v2
      # 设置环境
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
      # 还原包
      - name: Restore NuGet packages
        run: dotnet restore
      # 构建
      - name: Build
        run: dotnet build --configuration Release
      # 打包
      - name: Pack NuGet package
        run: |
          dotnet pack --configuration Release --no-build
      # 发布
      - name: Publish NuGet package
        run: |
          cd Src\Obase\Output
          dotnet nuget push *.nupkg --api-key ${{ secrets.NUGETAPIKEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
