name: Publish NuGet Package # Action名称

# 设置触发器 合并至master时触发
on:
  pull_request:
    branches:
      - master
  workflow_dispatch:
# 执行步骤
jobs:
  build-and-publish:
    runs-on: windows-latest

    steps:
      # 迁出
      - name: Checkout code
        uses: actions/checkout@v2

      # 设置环境
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
      # 还原包
      - name: Restore NuGet packages
        run: dotnet restore
      # 构建
      - name: Build
        run: dotnet build --configuration Release
      # 打包
      - name: Pack NuGet package
        run: |
          cd Obase4DotNet
          dotnet pack   --configuration Release --no-build
      
      # 发布
      - name: Publish NuGet package
        run: |
          cd Src\Obase\Output
          ls
